version: "3.9"

services:
  # -------------------- MongoDB --------------------
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # -------------------- PostgreSQL --------------------
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: etl_data
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # -------------------- Airflow --------------------
  airflow:
    build: ./airflow
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/data:/data
    ports:
      - "8080:8080"
    command: ["standalone"]
    depends_on:
      - postgres
      - mongo

  # -------------------- FastAPI --------------------
  fastapi:
    build: ./fastapi_app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://airflow:airflow@postgres:5432/etl_data
    depends_on:
      - postgres

  # -------------------- Streamlit --------------------
  streamlit:
    build: ./streamlit_app
    container_name: streamlit_app
    depends_on:
      - fastapi
    ports:
      - "8501:8501"
    environment:
      FASTAPI_URL: http://fastapi:8000

volumes:
  mongo_data:
  pg_data:
